# Generated by Django 4.1.1 on 2022-10-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_book_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationUserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('bookmark', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(verbose_name=((1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Excellent'), (5, 'Awesome')))),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
