# Generated by Django 4.1.1 on 2022-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationuserbook',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Excellent'), (5, 'Awesome')]),
        ),
    ]
