# Generated by Django 4.1.1 on 2022-11-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_relationuserbook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationuserbook',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Excellent'), (5, 'Awesome')], null=True),
        ),
    ]
