# Generated by Django 4.1.1 on 2022-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_relationuserbook_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationuserbook',
            name='review',
            field=models.CharField(default=False, max_length=256, null=True),
        ),
    ]
